import { normaliseText } from '@sah/core';

/**
 * Generates CustomFiles.ini and CustomFiles.lua.
 *
 * The section names and semantics come from the Custom Files hack
 * documentation:
 *   [Miscellaneous]      OccludedPath, ReadOnly, SuppressedPath
 *   [PathRedirections]   redirect one path to another
 *   [PathHandlers]       run a Lua script when the game requests a path
 *   [AdditionalFiles]    load an extra file alongside the original
 *
 * Path handler keys are game paths and therefore backslashed. The
 * documentation's own example escapes them (`scripts\\missions\\...`), and this
 * generator matches that form exactly.
 */

export interface PathHandlerEntry {
  /** Game-side path being handled, e.g. `scripts\missions\level01\m0i.mfk`. */
  gamePath: string;
  /** Mod-relative path of the Lua script, forward slashes. */
  scriptPath: string;
}

export interface CustomFilesIniOptions {
  pathHandlers: PathHandlerEntry[];
}

/** Escapes a game path the way the Custom Files documentation writes them. */
function escapeIniPath(gamePath: string): string {
  return gamePath.replace(/\\/g, '\\\\');
}

export function generateCustomFilesIni(options: CustomFilesIniOptions): string {
  const lines: string[] = [];

  lines.push('; Generated by the Springfield After Hours Toolkit.');
  lines.push('; Do not edit by hand — edit the campaign YAML and rebuild.');

  if (options.pathHandlers.length > 0) {
    lines.push('');
    lines.push('; Each entry makes the game run a Lua script when it requests the file on');
    lines.push('; the left. The script writes the MFK/CON content through Game.lua.');
    lines.push('[PathHandlers]');
    const sorted = [...options.pathHandlers].sort((a, b) => a.gamePath.localeCompare(b.gamePath));
    for (const handler of sorted) {
      lines.push(`${escapeIniPath(handler.gamePath)}=${handler.scriptPath}`);
    }
  }

  return normaliseText(lines.join('\n'));
}

export interface CustomFilesLuaOptions {
  /** Whether to load GameUtils.lua in addition to Game.lua. */
  includeGameUtils: boolean;
  /** Mod-relative directory holding the upstream Lua libraries. */
  libraryDirectory: string;
  campaignTitle: string;
  /** True when the pinned Game.lua has not been installed into the mod. */
  gameLuaMissing: boolean;
}

/**
 * Generates CustomFiles.lua.
 *
 * This file executes as soon as the mod loads, and its job is to make the
 * `Game` table available to every path handler script. The `dofile(GetModPath()
 * .. "/Resources/lib/Game.lua")` form is taken verbatim from Game.lua's README.
 */
export function generateCustomFilesLua(options: CustomFilesLuaOptions): string {
  const lines: string[] = [];

  lines.push('-- Generated by the Springfield After Hours Toolkit.');
  lines.push('-- Do not edit by hand — edit the campaign YAML and rebuild.');
  lines.push(`-- Campaign: ${options.campaignTitle}`);
  lines.push('');
  lines.push("-- Game.lua is Donut Team's MIT-licensed library. It is NOT distributed by");
  lines.push('-- the toolkit; it is installed into this mod from a pinned upstream commit.');
  lines.push('-- See Resources/lib/LICENSE-game-lua.md.');

  if (options.gameLuaMissing) {
    lines.push('');
    lines.push('-- ------------------------------------------------------------------');
    lines.push('-- WARNING: Game.lua was NOT present when this mod was built.');
    lines.push('-- The mission scripts in Resources/scripts will fail without it.');
    lines.push('-- Run "npm run upstream:fetch" in the toolkit, then rebuild.');
    lines.push('-- ------------------------------------------------------------------');
  }

  lines.push('');
  lines.push(`dofile(GetModPath() .. "/${options.libraryDirectory}/Game.lua")`);
  if (options.includeGameUtils) {
    lines.push(`dofile(GetModPath() .. "/${options.libraryDirectory}/GameUtils.lua")`);
  }

  return normaliseText(lines.join('\n'));
}
