import { normaliseText } from '@sah/core';
import type { Campaign } from '@sah/schemas';

/**
 * Generates Meta.ini.
 *
 * Every key emitted here appears in Donut Team's "Configuring Mods"
 * documentation. Keys are emitted in the documented order, and repeated keys
 * (Category, RequiredHack, AuthorGroup) use the documented repeat form rather
 * than a comma-separated list.
 *
 * The documentation states a mod must contain at least a [Miscellaneous]
 * section to be considered valid, and strongly recommends Title and
 * InternalName; all three are always written.
 */

export interface MetaIniOptions {
  campaign: Campaign;
  /** Hack names (Meta.ini spelling) the build determined are required. */
  requiredHacks: string[];
  /** Toolkit version, written as a comment for traceability. */
  generatorVersion: string;
}

function escapeIniValue(value: string): string {
  // Meta.ini uses \n for newlines within a value.
  return value.replace(/\r?\n/g, '\\n');
}

export function generateMetaIni(options: MetaIniOptions): string {
  const { campaign, requiredHacks } = options;
  const lines: string[] = [];

  lines.push('; Generated by the Springfield After Hours Toolkit.');
  lines.push('; Do not edit by hand — edit the campaign YAML and rebuild.');
  lines.push('');
  lines.push('[Miscellaneous]');
  lines.push(`Title=${escapeIniValue(campaign.title)}`);
  lines.push(`InternalName=${campaign.internalName}`);
  lines.push(`Description=${escapeIniValue(campaign.description)}`);
  lines.push(`Version=${campaign.version}`);

  for (const category of campaign.categories) {
    lines.push(`Category=${escapeIniValue(category)}`);
  }

  lines.push(`Main=${campaign.main ? 1 : 0}`);

  if (campaign.compatibility.requiredLauncherVersion) {
    lines.push(`RequiredLauncher=${campaign.compatibility.requiredLauncherVersion}`);
  }

  for (const hack of requiredHacks) {
    lines.push(`RequiredHack=${hack}`);
  }

  lines.push(`SupportsEnglish=${campaign.compatibility.supportsEnglish ? 1 : 0}`);
  lines.push(`SupportsDemo=${campaign.compatibility.supportsDemo ? 1 : 0}`);
  lines.push(`SupportsInternational=${campaign.compatibility.supportsInternational ? 1 : 0}`);
  lines.push(`SupportsBestSellerSeries=${campaign.compatibility.supportsBestSellerSeries ? 1 : 0}`);

  // Author groups must be declared before the [Author] sections that use them,
  // because the documentation states the order of AuthorGroup controls display
  // order.
  const groups = [...new Set(campaign.authors.map((a) => a.group).filter(Boolean))] as string[];
  for (const group of groups) {
    lines.push(`AuthorGroup=${escapeIniValue(group)}`);
  }

  for (const author of campaign.authors) {
    lines.push('');
    lines.push('[Author]');
    lines.push(`Name=${escapeIniValue(author.name)}`);
    if (author.website) lines.push(`Website=${author.website}`);
    if (author.notes) lines.push(`Notes=${escapeIniValue(author.notes)}`);
    if (author.group) lines.push(`Group=${escapeIniValue(author.group)}`);
    lines.push(`Credits=${author.credits ? 1 : 0}`);
  }

  return normaliseText(lines.join('\n'));
}
