import { DIAGNOSTIC_CODES, type Diagnostic } from '@sah/core';
import { referenceId } from '@sah/schemas';
import type { Mission, Reference, RegistryKind, Stage } from '@sah/schemas';
import { resolveRecord, type RegistrySet } from '@sah/registry';
import { GameLuaEmitter, type LuaArgument } from './emitter.js';

/**
 * Turns a mission into a Lua script that drives Game.lua.
 *
 * Every command this emitter produces is checked against the command registry
 * (which is derived from Game.lua's own tables) for argument count and scope
 * before it is written. A generated script therefore cannot contain a command
 * that does not exist, or one used in the wrong scope.
 */

export interface EmitMissionResult {
  lua: string;
  diagnostics: Diagnostic[];
  /** Registry record ids that contributed to this script, for the manifest. */
  usedRecords: Array<{ kind: RegistryKind; id: string }>;
}

interface EmitContext {
  emitter: GameLuaEmitter;
  registries: RegistrySet;
  diagnostics: Diagnostic[];
  used: Array<{ kind: RegistryKind; id: string }>;
  file: string;
}

export function emitMission(
  mission: Mission,
  registries: RegistrySet,
  file: string,
): EmitMissionResult {
  const emitter = new GameLuaEmitter();
  const context: EmitContext = { emitter, registries, diagnostics: [], used: [], file };

  emitter.comment('Generated by the Springfield After Hours Toolkit. Do not edit by hand.');
  emitter.comment(`Mission: ${mission.id} — ${mission.title}`);
  emitter.comment(
    "This script calls into Donut Team's Game.lua, which must be loaded by CustomFiles.lua.",
  );
  emitter.blank();

  // --- Mission scope ---------------------------------------------------------
  emitter.open('Mission', 'SelectMission', [mission.gameMissionName]);
  note(context, 'commands', 'select-mission');

  if (mission.resetPlayerInCarLocator) {
    const locator = resolveGameCode(context, mission.resetPlayerInCarLocator, 'locators');
    if (locator !== undefined) {
      emitChecked(context, 'SetMissionResetPlayerInCar', [locator], 'Mission');
    }
  }

  if (mission.dynaLoadData !== undefined) {
    emitChecked(context, 'SetDynaLoadData', [mission.dynaLoadData], 'Mission');
  }

  if (mission.pedGroup !== undefined) {
    emitChecked(context, 'UsePedGroup', [mission.pedGroup], 'Mission');
  }

  // --- Stages ----------------------------------------------------------------
  for (const stage of mission.stages) {
    emitter.blank();
    emitter.comment(`Stage: ${stage.id}${stage.title ? ` — ${stage.title}` : ''}`);

    // AddStage accepts 0-7 arguments. This toolkit emits none, because the
    // meaning of those arguments is not documented anywhere it has read, and
    // copying a value from an example without understanding it would be a guess.
    emitter.open('Stage', 'AddStage');
    note(context, 'commands', 'add-stage');

    if (stage.resetToHere) {
      emitChecked(context, 'RESET_TO_HERE', [], 'Stage');
    }
    if (stage.hudIcon) {
      const icon = resolveGameCode(context, stage.hudIcon, 'hud-icons');
      if (icon !== undefined) emitChecked(context, 'SetHUDIcon', [icon], 'Stage');
    }
    if (stage.stageMessageIndex !== undefined) {
      emitChecked(context, 'SetStageMessageIndex', [stage.stageMessageIndex], 'Stage');
    }
    if (stage.timeLimitSeconds !== undefined) {
      emitChecked(context, 'SetStageTime', [stage.timeLimitSeconds], 'Stage');
    }

    emitObjective(context, stage);
    emitConditions(context, stage);

    for (const raw of stage.rawCommands) {
      emitChecked(context, raw.command, raw.args as LuaArgument[], 'Stage');
    }

    emitter.close('Stage', 'CloseStage');
    note(context, 'commands', 'close-stage');
  }

  emitter.blank();
  emitter.close('Mission', 'CloseMission');
  note(context, 'commands', 'close-mission');

  emitter.assertBalanced();

  return {
    lua: emitter.toString(),
    diagnostics: context.diagnostics,
    usedRecords: dedupe(context.used),
  };
}

function emitObjective(context: EmitContext, stage: Stage): void {
  const { emitter } = context;
  const objective = stage.objective;

  const objectiveName = objective.type === 'raw' ? objective.objective : objective.type;

  emitter.open('Objective', 'AddObjective', [objectiveName]);
  note(context, 'commands', 'add-objective');
  note(context, 'objectives', objective.type === 'raw' ? objectiveName : objective.type);

  if (objective.type === 'raw') {
    for (const entry of objective.commands) {
      emitChecked(context, entry.command, entry.args as LuaArgument[], 'Objective');
    }
  }

  emitter.close('Objective', 'CloseObjective');
  note(context, 'commands', 'close-objective');
}

function emitConditions(context: EmitContext, stage: Stage): void {
  const { emitter } = context;
  for (const condition of stage.conditions) {
    emitter.open('Condition', 'AddCondition', [condition.type]);
    note(context, 'commands', 'add-condition');
    note(context, 'conditions', condition.type);
    emitter.close('Condition', 'CloseCondition');
    note(context, 'commands', 'close-condition');
  }
}

/**
 * Emits a command only after confirming it exists and is being used legally.
 *
 * A failure here is a bug in the toolkit rather than in the campaign — the
 * validator should already have rejected bad input — so it produces an error
 * diagnostic and emits nothing rather than writing a broken script.
 */
function emitChecked(
  context: EmitContext,
  command: string,
  args: readonly LuaArgument[],
  scope: string,
): void {
  const resolved = resolveRecord(context.registries, 'commands', command);
  const record = resolved.record;

  if (!record) {
    context.diagnostics.push({
      code: DIAGNOSTIC_CODES.UNSUPPORTED_COMMAND,
      severity: 'error',
      message: `Refusing to emit unknown command "${command}".`,
      location: { file: context.file },
      reference: command,
      registry: 'commands',
    });
    return;
  }

  const minArgs = Number(record['minArgs'] ?? 0);
  const maxArgs = Number(record['maxArgs'] ?? 0);
  if (args.length < minArgs || args.length > maxArgs) {
    context.diagnostics.push({
      code: DIAGNOSTIC_CODES.COMMAND_ARITY,
      severity: 'error',
      message: `Refusing to emit "${record.displayName}" with ${args.length} argument(s); Game.lua accepts ${minArgs}–${maxArgs}.`,
      location: { file: context.file },
      reference: command,
      registry: 'commands',
    });
    return;
  }

  const requiresScope = record['requiresScope'];
  if (typeof requiresScope === 'string' && requiresScope !== scope) {
    context.diagnostics.push({
      code: DIAGNOSTIC_CODES.COMMAND_SCOPE,
      severity: 'error',
      message: `Refusing to emit "${record.displayName}" in ${scope} scope; it requires ${requiresScope} scope.`,
      location: { file: context.file },
      reference: command,
      registry: 'commands',
    });
    return;
  }

  context.emitter.call(record.displayName, args);
  note(context, 'commands', record.id);
}

/**
 * Resolves a reference to the identifier the GAME uses, not the id this toolkit
 * uses. Getting this wrong would emit a mod full of registry ids the game has
 * never heard of.
 */
function resolveGameCode(
  context: EmitContext,
  reference: Reference,
  kind: RegistryKind,
): string | undefined {
  const id = referenceId(reference);
  const resolved = resolveRecord(context.registries, kind, id);
  if (!resolved.record) {
    context.diagnostics.push({
      code: DIAGNOSTIC_CODES.UNRESOLVED_LOCATOR,
      severity: 'error',
      message: `Refusing to emit unresolved ${kind} reference "${id}".`,
      location: { file: context.file },
      reference: id,
      registry: kind,
    });
    return undefined;
  }
  note(context, kind, resolved.record.id);

  const gameCode = resolved.record.gameCode;
  if (!gameCode) {
    context.diagnostics.push({
      code: DIAGNOSTIC_CODES.REFERENCE_NOT_BUILDABLE,
      severity: 'error',
      message: `Registry record "${id}" has no gameCode, so the toolkit does not know what to write into the script.`,
      location: { file: context.file },
      reference: id,
      registry: kind,
      hint: 'Add a gameCode to the record, with provenance.',
    });
    return undefined;
  }
  return gameCode;
}

function note(context: EmitContext, kind: RegistryKind, id: string): void {
  context.used.push({ kind, id });
}

function dedupe(
  entries: Array<{ kind: RegistryKind; id: string }>,
): Array<{ kind: RegistryKind; id: string }> {
  const seen = new Set<string>();
  const out: Array<{ kind: RegistryKind; id: string }> = [];
  for (const entry of entries) {
    const key = `${entry.kind}:${entry.id}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(entry);
  }
  return out.sort((a, b) => `${a.kind}:${a.id}`.localeCompare(`${b.kind}:${b.id}`));
}
